apiVersion: v1
kind: Service
metadata:
  name: servico-vendas-veiculos
  labels:
    app: servico-vendas-veiculos
spec:
  selector:
    app: servico-vendas-veiculos
  ports:
    - port: 8082
      targetPort: 8082
      name: http
  type: ClusterIP
